name: arij_radio
description: "A professional Radio WebView application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  google_mobile_ads: ^5.2.0
  connectivity_plus: ^6.1.0

flutter:
  uses-material-design: true
